# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "78a602699150bda4e49a40861707d500"
name = "its-under-it-all"
application_url = "https://join.itsunderitall.com"
embedded = true
handle = "its-under-it-all"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "customers/create" ]
  uri = "/api/webhooks/customers/create"

  [[webhooks.subscriptions]]
  topics = [ "customers/update" ]
  uri = "/api/webhooks/customers/update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,read_orders,write_orders,read_draft_orders,write_draft_orders"

[auth]
redirect_urls = [
  "https://its-under-it-all.replit.app/api/auth",
  "https://its-under-it-all.replit.app/auth/callback",
  "https://join.itsunderitall.com/api/auth",
  "https://join.itsunderitall.com/auth/callback"
]

[app_preferences]
url = "https://join.itsunderitall.com/settings"

[app_proxy]
url = "https://join.itsunderitall.com"
subpath = "wholesale"
prefix = "apps"



