# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "78a602699150bda4e49a40861707d500"
name = "its-under-it-all"
application_url = "https://join.itsunderitall.com"
embedded = true
handle = "its-under-it-all"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "customers/create" ]
  uri = "/api/webhooks/customers/create"

  [[webhooks.subscriptions]]
  topics = [ "customers/update" ]
  uri = "/api/webhooks/customers/update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,read_orders,write_orders,read_draft_orders,write_draft_orders"

[auth]
redirect_urls = [
  "https://its-under-it-all.replit.app/api/auth",
  "https://its-under-it-all.replit.app/auth/callback",
  "https://join.itsunderitall.com/api/auth",
  "https://join.itsunderitall.com/auth/callback"
]

[app_preferences]
url = "https://join.itsunderitall.com/settings"

[app_proxy]
url = "https://join.itsunderitall.com"
subpath = "wholesale"
prefix = "apps"

# Single Wholesale Link - Clarity CRM Account ID
[customer.metafields.app.wholesale_clarity_id]
type = "single_line_text_field"
name = "Wholesale Account ID (Clarity CRM)"
description = "Links customer to their wholesale account in Clarity CRM (e.g., AC000930)"

  [customer.metafields.app.wholesale_clarity_id.access]
  storefront = "public_read"
  customer_account = "read_write"
  admin = "merchant_read_write"

# Wholesale Company Name
[customer.metafields.app.wholesale_name]
type = "single_line_text_field"
name = "Wholesale Company Name"
description = "The name of the wholesale company/account"

  [customer.metafields.app.wholesale_name.access]
  storefront = "public_read"
  customer_account = "read_write"
  admin = "merchant_read_write"

# Clarity Account Name
[customer.metafields.app.clarity_account_name]
type = "single_line_text_field"
name = "Clarity Account Name"
description = "Account name from Clarity CRM"

  [customer.metafields.app.clarity_account_name.access]
  storefront = "public_read"
  customer_account = "read_write"
  admin = "merchant_read_write"

# Clarity Contacts (JSON list)
[customer.metafields.app.clarity_contacts]
type = "json"
name = "Clarity Contacts"
description = "Customer reference list from Clarity CRM (JSON)"

  [customer.metafields.app.clarity_contacts.access]
  storefront = "public_read"
  customer_account = "read_write"
  admin = "merchant_read_write"

# UIA-ID (Internal Registration ID)
[customer.metafields.app.uia_id]
type = "single_line_text_field"
name = "UIA Registration ID"
description = "Internal wholesale registration UUID"

  [customer.metafields.app.uia_id.access]
  storefront = "public_read"
  customer_account = "read_write"
  admin = "merchant_read_write"



